---
sidebar: sidebar 
permalink: saved-search-capabilities.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network, search, criteria, solution , explorer 
summary: Sie können verschiedene Lösungen oder Konfigurationen über das Menü *gespeicherte Suche* laden, mit dem Sie zu zuvor gespeicherten Suchergebnissen, zuletzt gespeicherten Suchergebnissen und gespeicherten Konfigurationen navigieren können. 
---
= Gespeicherte Suchfunktionen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie können verschiedene Lösungen oder Konfigurationen über das Menü *gespeicherte Suche* laden, mit dem Sie zu zuvor gespeicherten Suchergebnissen, zuletzt gespeicherten Suchergebnissen und gespeicherten Konfigurationen navigieren können.

Die Registerkarte *Suchkriterien* enthält Ihre gespeicherten Suchen. Auf dieser Registerkarte können Sie Suchen freigeben oder Suchen anzeigen, die andere für Sie freigegeben haben. Die Registerkarte *Konfiguration* enthält Ihre gespeicherten Konfigurationen. Auf dieser Registerkarte können Sie Konfigurationen freigeben oder Konfigurationen anzeigen, die andere für Sie freigegeben haben.

Die Registerkarte *Letzte Suche* enthält die letzten 30 Sätze von Suchkriterien, vom letzten bis zum ältesten. Es listet auch den *Suchfluss* auf, der die Ursprungsseite angibt, die *Liste und Suche, Solution Explorer oder Advanced Search* sein kann. Die Kriterien werden automatisch gespeichert. Diese Seite listet auch das *Datum der letzten Änderung* einer gespeicherten oder letzten Suche auf. Sie können *Load* eine Suche aus der Liste laden, um die Kriterien bzw. Konfigurationen anzuzeigen.
